# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:18-alpine AS builder

# Set up the working directory
WORKDIR /app

# Copy package.json and package-lock.json for dependency installation
COPY package.json package-lock.json ./

# Install dependencies, including dev dependencies for building
RUN npm install --ignore-scripts

# Copy the rest of the application files
COPY . .

# Build the TypeScript files
RUN npm run build

# Create the runtime image
FROM node:18-alpine

WORKDIR /app

# Copy the built files from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json /app/package-lock.json ./

# Set NODE_ENV to production
ENV NODE_ENV=production

# Install only the production dependencies
RUN npm ci --ignore-scripts --omit=dev

# Expose the necessary port (if any specified in the app, otherwise adjust accordingly)
EXPOSE 3000

# Command to run the server
ENTRYPOINT ["node", "build/index.js"]

# The environment variables for AWS credentials are expected to be provided at runtime
